### PR TITLE
Adding doi to list

### PR DESCRIPTION
**Pull request by kjschmidt913**
added DOI to .list() output

### CODE REVIEW

**Comment by blaiszik** [comment]
Looks great. Could you add it to the `_repr_html_` function as well if it exists? Then we will pull it in!

**Comment by kjschmidt913** [comment]
Good call! I added DOI to the `_repr_html_` function as a `<p>` element (I liked the spacing that added between the author line and the DOI line). Here's a preview of what that looks like:
Screen Shot 2022-02-09 at 11 44 36 AM

**Comment by ascourtas** [comment]
@kjschmidt913 @blaiszik is this done?

**Comment by kjschmidt913** [comment]
@ascourtas yes it is!

**Comment by ascourtas** [comment]
@kjschmidt913 ok I'll merge!

**Pull request merged**
