### PR TITLE
first refactor attempt

### PR DESCRIPTION
**Pull request by zk794**
re: [story 423](https://app.clubhouse.io/ai-for-materials-and-chemistry/story/423/pull-xtract-logic-into-a-separate-module-for-better-reusability)

### CODE REVIEW

**Comment by blaiszik** [comment]
@zk794 , could you pull out the config into one location and pass them in as either **kwargs or as a config dict?

```
         xtract_base_url = (
                 "http://xtract-crawler-4.eba-ghixpmdf.us-east-1.elasticbeanstalk.com"
             )

             # MDF Materials Data at NCSA
             source_ep_id = "82f1b5c6-6e9b-11e5-ba47-22000b92c6ec"
             base_url = "https://data.materialsdatafacility.org"
             folder_to_crawl = f"/foundry/{source_id}/"

             # This only matters if you want files grouped together.
             grouper = "matio"

```

**Comment by blaiszik** [comment]
Also @zk794 , can you create PRs from all of the branches into the `dev` branch rather than `main`?

**Comment by zk794** [comment]
@blaiszik How's this?

**Comment by blaiszik** [comment]
Looks good.

**Pull request merged**
