### PR TITLE
update jupyter notebook examples

### PR DESCRIPTION
**Pull request by zk794**
foundry_publication_example:
Changes:
  - Updated text in Data format and naming section -- removing text about specific foundry_dataframe.json naming convention
	(Not sure if the CSV reading line not being accepted is still accurate)
  - Updated example metadata to fit with the new format
  - Updated the data source link accordingly (now is the same as the one used for testing in test_foundry.py)
  - Added timestamps to the example publishes in title and short_name so we don't run into source_id publishing issues

model_publishing:
Changes
  - Changed the pip install to go off regardless of whether in Colab Environment or not, along with the text accompanying
  - Updated dataset to use ("_test_foundry_iris_dev_v2.1")
  - Updated the load_data() call in 'Loading Data and Training Module'

dataset_publishing:
Changes
  - Same exact changes as foundry_publication_example

iris:
  - updated metadata to match new format
  - changed the Installing Foundry section code to the pip install from requirements.txt. 
  - Removed “json” from requirements.txt

dendrite_segmentation:
  - updated metadata to match new format
  - changed “Installing Foundry” section text (renamed section “Installing Foundry and Other Modules”, and do pip install requirements.txt. 
  - Removed “json” from requirements.txt

### CODE REVIEW

**Comment by kjschmidt913** [comment]
It's difficult to see notebook changes on github since it shows the raw files in the code comparisons. I'm going to look at the notebooks but may slack you to set up a call for you to walk me through changes if I'm not sure what you did and why. I'll reach out tomorrow if I need that!

**Comment by kjschmidt913** [comment]
foundry_publication_example:
Looks great! Only change: clear the output from the pip install cell (the first code block). Could you put this notebook in the publishing_guides folder? Been meaning to move it there.

model_publishing:
Same thing- just clear the output from the pip installs. Otherwise, looks good! Could you put this notebook in the publishing_guides folder? Been meaning to move it there.

dataset_publishing:
Is this the exact same notebook as the foundry_publication_example? If so, you can delete foundry_publication_example since this one is named more specifically. If not, just clear the output of the pip install cell.

iris and dendrite_segmentation:
Looks great! Clear the output of the pip install cell. Does installing a requirement.txt file work in google colab? Just making sure this still can be run on google colab as well as locally.

**Comment by kjschmidt913** [comment]
Notebooks look great! Do you know what this merge conflict is about in foundry.py? I thought this branch was only for notebook changes. Is the change in that file on purpose?

**Comment by zk794** [comment]
@kjschmidt913 the foundry one was a silly thing, I was trying to make some branch but didn't have any actual changes to commit so I made a nonsense comment and I guess I forgot to delete it afterwards. It should match dev.

I'm not sure what the test_foundry.py change is, I think @ribhavb might know more.

**Comment by ribhavb** [comment]
AH so sorry for that, accidentally changed a line, changed it back, test_foundry.py should be all good now!

**Pull request merged**
