### PR TITLE
added resiliency for extra files in download

### PR DESCRIPTION
**Pull request by ribhavb**
in download, instead of checking whether downloaded directory contains exact amount of files as specified in metadata, now checks to make sure it downloads at least as many as specified in metadata for flexibility

### CODE REVIEW

**Review by blaiszik — CHANGES_REQUESTED** [review]
I wonder if a more robust approach to this would be to check the existence of the files specified in splits. 

There are two cases that I see:
1) **No splits exist.** Condition: there should be at least one file in the directory
2) **Splits exist.** Condition: There should be a file that corresponds exactly to the file specified in each split.

**Review by blaiszik — CHANGES_REQUESTED** [review]
Could you change the format() functions to Python f' strings?

**Comment by ascourtas** [comment]
@ribhavb @blaiszik is this PR ok now?

**Comment by blaiszik** [comment]
Should this be closed now that we have the other OOP PR? @ribhavb

**Comment by blaiszik** [comment]
I commented in the wrong chain here. Does this still need to be merged since the other download resiliency was merged?
@ribhavb

**Comment by ribhavb** [comment]
Nope! I'll close this now

**Pull request closed without merging**
